"""Initial baseline with worker fields

Revision ID: ef40c9a51668
Revises: 
Create Date: 2026-09-05 16:20:38.236453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef40c9a51668'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_updated', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crash_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('crash_probability', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('severity_label', sa.String(), nullable=True),
    sa.Column('sensor_data', sa.JSON(), nullable=True),
    sa.Column('was_manual', sa.Boolean(), nullable=True),
    sa.Column('sos_triggered', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_events_event_id'), 'crash_events', ['event_id'], unique=True)
    op.create_table('dispatch_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_id', sa.String(), nullable=False),
    sa.Column('sos_event_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('patient_lat', sa.Float(), nullable=False),
    sa.Column('patient_lng', sa.Float(), nullable=False),
    sa.Column('patient_user_id', sa.String(), nullable=True),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('route_url', sa.Text(), nullable=True),
    sa.Column('driver_sms_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_events_dispatch_id'), 'dispatch_events', ['dispatch_id'], unique=True)
    op.create_table('fir_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_templates_state'), 'fir_templates', ['state'], unique=True)
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('trauma_beds_total', sa.Integer(), nullable=True),
    sa.Column('trauma_beds_available', sa.Integer(), nullable=True),
    sa.Column('icu_beds_total', sa.Integer(), nullable=True),
    sa.Column('icu_beds_available', sa.Integer(), nullable=True),
    sa.Column('general_beds_available', sa.Integer(), nullable=True),
    sa.Column('blood_bank', sa.Boolean(), nullable=True),
    sa.Column('blood_types_available', sa.JSON(), nullable=True),
    sa.Column('has_trauma_center', sa.Boolean(), nullable=True),
    sa.Column('has_cath_lab', sa.Boolean(), nullable=True),
    sa.Column('has_neuro_unit', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('beds_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sos_event_id', sa.String(), nullable=True),
    sa.Column('crash_event_id', sa.String(), nullable=True),
    sa.Column('dispatch_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('crash_timestamp', sa.DateTime(), nullable=True),
    sa.Column('speed_at_impact', sa.Float(), nullable=True),
    sa.Column('medical_profile', sa.JSON(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('ambulance_name', sa.String(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fir_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    op.create_table('medical_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('disabilities', sa.JSON(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('insurance_provider', sa.String(), nullable=True),
    sa.Column('insurance_policy_no', sa.String(), nullable=True),
    sa.Column('digilocker_linked', sa.Boolean(), nullable=True),
    sa.Column('abha_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_profiles_user_id'), 'medical_profiles', ['user_id'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('licence_number', sa.String(length=100), nullable=False),
    sa.Column('licence_expiry', sa.Date(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_table('responder_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responder_uuid', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responder_assignments_id'), 'responder_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_responder_assignments_incident_id'), 'responder_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_responder_assignments_responder_uuid'), 'responder_assignments', ['responder_uuid'], unique=False)
    op.create_table('sos_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('medical_profile', sa.JSON(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_count', sa.Integer(), nullable=True),
    sa.Column('was_offline', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_events_event_id'), 'sos_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.create_table('tracking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sos_event_id', sa.String(), nullable=True),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('ambulance_name', sa.String(), nullable=True),
    sa.Column('initial_lat', sa.Float(), nullable=True),
    sa.Column('initial_lng', sa.Float(), nullable=True),
    sa.Column('latest_lat', sa.Float(), nullable=True),
    sa.Column('latest_lng', sa.Float(), nullable=True),
    sa.Column('location_updated', sa.DateTime(), nullable=True),
    sa.Column('contacts_notified', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('was_offline', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_sessions_session_id'), 'tracking_sessions', ['session_id'], unique=True)
    op.create_table('triage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('has_voice', sa.Boolean(), nullable=True),
    sa.Column('has_sensor_data', sa.Boolean(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('image_score', sa.Float(), nullable=True),
    sa.Column('nlp_score', sa.Float(), nullable=True),
    sa.Column('sensor_score', sa.Float(), nullable=True),
    sa.Column('final_severity', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('severity_label', sa.String(), nullable=True),
    sa.Column('shap_factors', sa.JSON(), nullable=True),
    sa.Column('was_offline', sa.Boolean(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('processing_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('feature_version', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_events_event_id'), 'triage_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_triage_events_job_id'), 'triage_events', ['job_id'], unique=False)
    op.create_table('triage_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_jobs_request_id'), 'triage_jobs', ['request_id'], unique=False)
    op.create_index(op.f('ix_triage_jobs_status'), 'triage_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_triage_jobs_user_id'), 'triage_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_triage_jobs_worker_id'), 'triage_jobs', ['worker_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=False),
    sa.Column('current_lng', sa.Float(), nullable=False),
    sa.Column('last_ping', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('dispatch_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_lat', sa.Float(), nullable=False),
    sa.Column('incident_lng', sa.Float(), nullable=False),
    sa.Column('incident_address', sa.String(length=500), nullable=False),
    sa.Column('assigned_ambulance_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_ambulance_id'], ['ambulances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_requests_id'), 'dispatch_requests', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['dispatch_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_dispatch_requests_id'), table_name='dispatch_requests')
    op.drop_table('dispatch_requests')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_triage_jobs_worker_id'), table_name='triage_jobs')
    op.drop_index(op.f('ix_triage_jobs_user_id'), table_name='triage_jobs')
    op.drop_index(op.f('ix_triage_jobs_status'), table_name='triage_jobs')
    op.drop_index(op.f('ix_triage_jobs_request_id'), table_name='triage_jobs')
    op.drop_table('triage_jobs')
    op.drop_index(op.f('ix_triage_events_job_id'), table_name='triage_events')
    op.drop_index(op.f('ix_triage_events_event_id'), table_name='triage_events')
    op.drop_table('triage_events')
    op.drop_index(op.f('ix_tracking_sessions_session_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_event_id'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_responder_assignments_responder_uuid'), table_name='responder_assignments')
    op.drop_index(op.f('ix_responder_assignments_incident_id'), table_name='responder_assignments')
    op.drop_index(op.f('ix_responder_assignments_id'), table_name='responder_assignments')
    op.drop_table('responder_assignments')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_medical_profiles_user_id'), table_name='medical_profiles')
    op.drop_table('medical_profiles')
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_fir_templates_state'), table_name='fir_templates')
    op.drop_table('fir_templates')
    op.drop_index(op.f('ix_dispatch_events_dispatch_id'), table_name='dispatch_events')
    op.drop_table('dispatch_events')
    op.drop_index(op.f('ix_crash_events_event_id'), table_name='crash_events')
    op.drop_table('crash_events')
    op.drop_table('ambulance_providers')
    # ### end Alembic commands ###
